# Generated by Django 5.2.5 on 2025-08-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='options',
            field=models.TextField(blank=True, help_text='Enter comma separated values for select field (e.g. Python, Java, JS, React)', null=True),
        ),
    ]
