# Generated by Django 5.2.5 on 2025-08-20 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsbuilder', '0003_department_alter_dynamicform_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicform',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='formsbuilder.department', unique=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('textarea', 'Textarea'), ('select', 'Select')], max_length=50),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
