# Generated by Django 5.2.5 on 2025-08-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsbuilder', '0004_alter_dynamicform_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dep_email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='dep_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
