# Generated by Django 5.2.5 on 2025-08-20 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsbuilder', '0006_alter_dynamicform_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentadminassignment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formsbuilder.department'),
        ),
    ]
