# Generated by Django 5.2.5 on 2025-08-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsbuilder', '0007_alter_departmentadminassignment_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('textarea', 'Textarea'), ('select', 'Select'), ('password', 'Password'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('file', 'File Upload'), ('range', 'Range Slider'), ('tel', 'Telephone'), ('url', 'URL'), ('hidden', 'Hidden'), ('color', 'Color Picker'), ('submit', 'Submit Button'), ('reset', 'Reset Button'), ('button', 'Button')], max_length=50),
        ),
    ]
