# Generated by Django 5.2.5 on 2025-08-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsbuilder', '0008_alter_formfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='options',
            field=models.TextField(blank=True, help_text='Comma-separated options for select, checkbox, or radio fields', null=True),
        ),
    ]
