# Generated by Django 5.2.5 on 2025-08-21 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsbuilder', '0009_alter_formfield_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='max_file_size_mb',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum file size in megabytes (for file fields only).', null=True, verbose_name='Max File Size (MB)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dep_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='department',
            name='dep_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='departmentadminassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dynamicform',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsbuilder.department'),
        ),
        migrations.AlterField(
            model_name='dynamicform',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('textarea', 'Textarea'), ('select', 'Select'), ('password', 'Password'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('file', 'File'), ('range', 'Range'), ('tel', 'Telephone'), ('url', 'URL'), ('hidden', 'Hidden'), ('color', 'Color'), ('submit', 'Submit'), ('reset', 'Reset'), ('button', 'Button')], max_length=50),
        ),
    ]
