# Generated by Django 5.2.5 on 2025-08-25 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsbuilder', '0011_alter_enquiry_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Chatbot Settings',
                'verbose_name_plural': 'Chatbot Settings',
            },
        ),
        migrations.CreateModel(
            name='ChatbotQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsbuilder.department')),
            ],
        ),
    ]
