# Generated by Django 5.2.5 on 2025-08-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsbuilder', '0012_chatbotsettings_chatbotqa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotsettings',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Chatbot status'),
        ),
    ]
