# Generated by Django 5.2.5 on 2025-08-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsbuilder', '0013_alter_chatbotsettings_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dep_img',
            field=models.ImageField(blank=True, null=True, upload_to='department_images/'),
        ),
    ]
